import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import fs from "fs";
import path from "path";


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const env = JSON.parse(fs.readFileSync('.env'));

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
})
.then(() => {
	['main.js', /*'manifest.json'*/].forEach(fname => {
		fs.copyFile(fname, path.join(env.target_dir, fname), (e) => {if (e) throw e})
	});
})
.catch(() => process.exit(1))

