import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
let pluginDir = "."
try {
	pluginDir = JSON.parse(fs.readFileSync('.env')).target_dir
} catch(e) {
	console.log("failed to read .env file, compile to current directory")
}


// see https://github.com/evanw/esbuild/issues/408#issuecomment-757555771
let wasmPlugin = {
	name: 'wasm',
	setup(build) {
		// Resolve ".wasm" files to a path with a namespace
		build.onResolve({ filter: /\.wasm$/ }, args => {
			if (args.resolveDir === '') {
				return // Ignore unresolvable paths
			}
			return {
				path: path.isAbsolute(args.path) ? args.path : path.join(args.resolveDir, args.path),
				namespace: 'wasm-binary',
			}
		})

		// Virtual modules in the "wasm-binary" namespace contain the
		// actual bytes of the WebAssembly file. This uses esbuild's
		// built-in "binary" loader instead of manually embedding the
		// binary data inside JavaScript code ourselves.
		build.onLoad({ filter: /.*/, namespace: 'wasm-binary' }, async (args) => ({
			contents: await fs.promises.readFile(args.path),
			loader: 'binary',
		}))
	},
}


function copyIfChanged(srcfile, destfile) {
	fs.watchFile(srcfile, { interval: 1000 }, (c, p) => {
		if (c.mtimeMs > p.mtimeMs) {
			console.log("[watch] copy newer styles.css")
			fs.copyFileSync(srcfile, destfile)
		}
	})
}

let watching = false;

let copyFile = {
	name: 'copy-plugin-files',
	setup(build) {
		build.onStart(() => {
			if (prod || watching) { return; }
			watching = true;
			copyIfChanged("./styles.css", path.join(pluginDir, "styles.css"))
		})
	},
}

esbuild.build({
	banner: {
		js: banner,
	},
	plugins: [wasmPlugin, copyFile],
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian', 
		'electron',
		"codemirror",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/commands",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/view",
		...builtins
	],
	format: 'cjs',
	watch: !prod,
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(pluginDir, 'main.js'),
}).catch(() => process.exit(1))

