[package]
name = "charliberty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.57"
pest = "2.1.3"
pest_derive = "2.1.0"
wasm-bindgen = "0.2.100"
